### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by NanNanCHN** [Treri/dotfile#1]
我需要install 哪几个有必要的task?

**Comment by ik0r** [comment]
看你需要什么了. 我觉得task的名字应该能够让你知道这个task是干什么的

比如zsh, 基础的就是 zsh_rc, 会帮你安装 oh-my-zsh 和一些基础插件, 如果你需要用比如 fasd thefuck fzf等插件的话, 就再安装 `zsh_plugins_fasd`, `zsh_plugins_fzf`, `zsh_plugins_thefuck` 等task

再比如vim, 如果只是想要基础的配置文件, `vim_rc` 就足够了. 这个是不带任何插件的. 如果你需要用一些插件, 可以安装 `vim_plugins`. 这一个task还有很多分组, 你可以在plugins相关的配置文件中指明你想要使用哪些分组的插件.

这些都是我平时使用的过程中, 积累出的一些task, 兼顾我的使用习惯还有通用性. 在配置文件中, 尽量不掺杂我个人的一些东西
